## Practice 

**Завдання:**
Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.
-   Знайдіть мінімальне та максимальне значення в усьому масиві.
-   Визначте індекси мінімального та максимального елементів
    (наприклад: (рядок, стовпець)).
-   Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [13]:
import numpy as np
rng = np.random.default_rng()
array_floats = rng.random(100).reshape(10, 10).round(3)
print(f"Array with random floating numbers: {array_floats}")

Array with random floating numbers: [[0.824 0.98  0.912 0.042 0.563 0.159 0.101 0.769 0.866 0.786]
 [0.447 0.675 0.492 0.158 0.809 0.967 0.026 0.026 0.543 0.311]
 [0.298 0.506 0.596 0.637 0.803 0.245 0.749 0.55  0.743 0.059]
 [0.873 0.18  0.372 0.627 0.449 0.899 0.949 0.738 0.205 0.518]
 [0.635 0.078 0.708 0.337 0.186 0.792 0.887 0.564 0.674 0.949]
 [0.707 0.465 0.835 0.686 0.069 0.852 0.868 0.474 0.537 0.685]
 [0.084 0.446 0.909 0.111 0.487 0.834 0.329 0.771 0.01  0.904]
 [0.359 0.923 0.356 0.512 0.671 0.49  0.609 0.262 0.263 0.807]
 [0.33  0.302 0.809 0.972 0.364 0.864 0.386 0.464 0.616 0.949]
 [0.267 0.55  0.828 0.454 0.815 0.311 0.535 0.768 0.877 0.901]]


In [15]:
print(f'Min value: {array_floats.min()}')
print(f'Index of min elem (rows, cols): {np.unravel_index(array_floats.argmin(), array_floats.shape)}')
print(f'Max value: {array_floats.max()}')
print(f'Index of max elem (rows, cols): {np.unravel_index(array_floats.argmax(), array_floats.shape)}')

Min value: 0.01
Index of min elem (rows, cols): (np.int64(6), np.int64(8))
Max value: 0.98
Index of max elem (rows, cols): (np.int64(0), np.int64(1))
