## Practice

**Завдання:**
Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
-   Виведіть масив у читабельному вигляді (у вигляді таблиці).
-   Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
-   Визначте загальне середнє значення масиву.
-   Виведіть усі результати в зручному вигляді   
    (наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [12]:
import numpy as np
rng = np.random.default_rng()
random_numbers = rng.integers(0, 50, size=16)
reshape_array = random_numbers.reshape(4, 4)
print(f'Array 4x4:{reshape_array}')

Array 4x4:[[34 11 20 48]
 [32 45 33 19]
 [32 23 22 39]
 [47 12  2 32]]


In [13]:
print(f"Average value of all array: {reshape_array.mean()}")
print(f"Sum by columns: {reshape_array.sum(axis=0)}")
print(f"Sum by rows: {reshape_array.sum(axis=1)}" )

Average value of all array: 28.1875
Sum by columns: [145  91  77 138]
Sum by rows: [113 129 116  93]
