## Practice

**Завдання:**
Створіть масив розміром 3×5, заповнений числами від 0 до 14.

-   Виведіть вихідний масив.
-   Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
-   Застосуйте операцію reshape, щоб отримати масив 5×3.
-   Відобразіть результати на екран.

In [10]:
import numpy as np
array = np.arange(15).reshape(3, 5)
print(f"An array 3x5: {array}")

An array 3x5: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [11]:
print(f"Transponsed array: {array.T}")

Transponsed array: [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [12]:
print(f'Reshaped array: {array.reshape(5,3)}')

Reshaped array: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
